common: configure usb gadget NCM through configfs
No usb gadget NCM function was configured.
This is causing the following VTS test to fail:
	com.android.tests.usbgadget.VtsHalUsbGadgetV2_0HostTest#testAndroidNcm
with the error:
	java.lang.AssertionError: NCM not present

Create the NCM configfs function.
Note: the NCM function is gs9:
	gs6 is for ACM
	gs7 is for DM
	gs8 is for UTS

Signed-off-by: Maxime Fournier <mfournier@baylibre.com>