auto: am62x: Switch to 64bits as well
commit fb00dfac9a7c ("am62x: migrate in 64bits only") migrated AM62X to
64-bits only userspace. However, we did not update the car variant.

Because of this, we see:

$ lunch am62x_car-ap3a-userdebug
error: Building a 32-bit-app-only product on a 64-bit device.

Fix the build error by including core_64_bit_only.

Test: source build/envsetup.sh && lunch am62x_car-ap3a-userdebug
Fixes: fb00dfac9a7c ("am62x: migrate in 64bits only")
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>